### ISSUE TITLE
Your code repository does not contain file named LICENSE

### ISSUE THREAD

**Issue by Farfeght** [daybrush/utils#3]
Hi
I would love to use your library, but there is no LICENSE file to state who can or cannot use your library.

Can I ask you to put this information into your repository, or at least state me what is the intended license?

NPM site ( [https://www.npmjs.com/package/@daybrush/utils/v/1.4.0](https://www.npmjs.com/package/@daybrush/utils/v/1.4.0) ) states the license to be MIT, but your code does not reference this in any way.

BR.
Mikko Eronen

**Comment by daybrush** [comment]
@Farfeght 


I'm sorry for not seeing the issue for a long time.

License was added.

Thank you :)

**Comment by Farfeght** [comment]
Thank you , this is awesome ! 👍
